// Code generated from condor_adstash convert.py attribute tables. DO NOT EDIT BY HAND.
// Regenerate with: python3 gen_attrs.py .../src/condor_scripts/adstash/convert.py > attrs.go

package opensearchsync

// required_attrs (11 attrs)
var requiredAttrs = []string{
	"ClusterId",
	"CompletionDate",
	"EnteredCurrentStatus",
	"EpochWriteDate",
	"GlobalJobId",
	"JobStatus",
	"JobUniverse",
	"LastRemoteHost",
	"MyType",
	"ProcId",
	"RemoteHost",
}

// indexed_keyword_attrs (74 attrs)
var indexedKeywordAttrs = []string{
	"AccountingGroup",
	"AcctGroup",
	"AcctGroupUser",
	"AssignedGPUs",
	"AutoClusterId",
	"AWSRegion",
	"BatchProject",
	"BatchQueue",
	"CloudLabelNames",
	"ConcurrencyLimits",
	"CondorPlatform",
	"CondorVersion",
	"CUDAVersion",
	"DAGNodeName",
	"DAGParentNodeNames",
	"DockerImage",
	"FileSystemDomain",
	"GLIDEIN_Entry_Name",
	"GlideinClient",
	"GlideinEntryName",
	"GlideinFactory",
	"GlideinFrontendName",
	"GlideinName",
	"GlobalJobId",
	"GridJobId",
	"GridJobStatus",
	"GridResource",
	"HoldKillSig",
	"JobBatchName",
	"JobDescription",
	"JobKeyword",
	"JobState",
	"KillSig",
	"LastRemoteHost",
	"LastRemotePool",
	"MATCH_EXP_JOB_GLIDECLIENT_Name",
	"MATCH_EXP_JOB_GLIDEIN_ClusterId",
	"MATCH_EXP_JOB_GLIDEIN_Entry_Name",
	"MATCH_EXP_JOB_GLIDEIN_Factory",
	"MATCH_EXP_JOB_GLIDEIN_Name",
	"MATCH_EXP_JOB_GLIDEIN_Schedd",
	"MATCH_EXP_JOB_GLIDEIN_SEs",
	"MATCH_EXP_JOB_GLIDEIN_Site",
	"MATCH_EXP_JOB_GLIDEIN_SiteWMS_JobId",
	"MATCH_EXP_JOB_GLIDEIN_SiteWMS_Queue",
	"MATCH_EXP_JOB_GLIDEIN_SiteWMS_Slot",
	"MATCH_EXP_JOB_GLIDEIN_SiteWMS",
	"MATCH_EXP_JOBGLIDEIN_ResourceName",
	"MyType",
	"NTDomain",
	"OAuthServicesNeeded",
	"Owner",
	"ProjectName",
	"RemoteHost",
	"RemotePool",
	"RemoveKillSig",
	"ScheddName",
	"ShouldTransferFiles",
	"SingularityImage",
	"StartdName",
	"StartdSlot",
	"Status",
	"SubmitterGlobalJobId",
	"SubmitterGroup",
	"SubmitterNegotiatingGroup",
	"TargetType",
	"Universe",
	"User",
	"WhenToTransferOutput",
	"x509UserProxyEmail",
	"x509UserProxyFirstFQAN",
	"x509UserProxyFQAN",
	"x509UserProxySubject",
	"x509UserProxyVOName",
}

// noindex_keyword_attrs (57 attrs)
var noindexKeywordAttrs = []string{
	"AllRemoteHosts",
	"AppendFiles",
	"Args",
	"Arguments",
	"Cmd",
	"CompressFiles",
	"ContainerServiceNames",
	"DAGManNodesLog",
	"DAGManNodesMask",
	"DontEncryptInputFiles",
	"DontEncryptOutputFiles",
	"EncryptInputFiles",
	"EncryptOutputFiles",
	"Err",
	"ExitReason",
	"FetchFiles",
	"FileRemaps",
	"HoldReason",
	"In",
	"Iwd",
	"JOBGLIDEIN_ResourceName",
	"LastHoldReason",
	"LastRejMatchReason",
	"LocalFiles",
	"ManifestDir",
	"NotifyUser",
	"OnExitHoldReason",
	"OnExitRemoveReason",
	"OtherJobRemoveRequirements",
	"Out",
	"OutputDestination",
	"PeriodicHoldReason",
	"PeriodicReleaseReason",
	"PeriodicRemoveReason",
	"PostCmd",
	"PreCmd",
	"PublicInputFiles",
	"ReleaseReason",
	"RemoteIwd",
	"RemoveReason",
	"Requirements",
	"RootDir",
	"StartdIpAddr",
	"StartdPrincipal",
	"StarterIpAddr",
	"StarterPrincipal",
	"SubmitEventNotes",
	"SubmitEventUserNotes",
	"TransferCheckpoint",
	"TransferInput",
	"TransferInputRemaps",
	"TransferIntermediate",
	"TransferOutput",
	"TransferOutputRemaps",
	"TransferPlugins",
	"UserLog",
	"UserLogFile",
}

// float_attrs (8 attrs)
var floatAttrs = []string{
	"CPUsUsage",
	"GPUsAverageUsage",
	"GPUsMemoryUsage",
	"JobBatchId",
	"JobDuration",
	"NetworkInputMb",
	"NetworkOutputMb",
	"Rank",
}

// int_attrs (136 attrs)
var intAttrs = []string{
	"AutoClusterId",
	"BatchRuntime",
	"BlockReadKbytes",
	"BlockReads",
	"BlockWriteKbytes",
	"BlockWrites",
	"BufferBlockSize",
	"BufferSize",
	"BytesRecvd",
	"BytesSent",
	"ClusterId",
	"CommittedSlotTime",
	"CommittedSuspensionTime",
	"CommittedTime",
	"CoreSize",
	"CpusProvisioned",
	"CumulativeRemoteSysCpu",
	"CumulativeRemoteUserCpu",
	"CumulativeSlotTime",
	"CumulativeSuspensionTime",
	"CumulativeTransferTime",
	"CurrentHosts",
	"DAGManJobId",
	"DataLocationsCount",
	"DelegatedProxyExpiration",
	"DiskProvisioned",
	"DiskUsage_RAW",
	"DiskUsage",
	"ErrSize",
	"ExecutableSize_RAW",
	"ExecutableSize",
	"ExitCode",
	"ExitSignal",
	"ExitStatus",
	"GpusProvisioned",
	"HoldReasonCode",
	"HoldReasonSubCode",
	"ImageSize_RAW",
	"ImageSize",
	"IOWait",
	"JobLeaseDuration",
	"JobMaxRetries",
	"JobMaxVacateTime",
	"JobPid",
	"JobPrio",
	"JobRunCount",
	"JobStatus",
	"JobSuccessExitCode",
	"JobUniverse",
	"KeepClaimIdle",
	"KillSigTimeout",
	"LastHoldReasonCode",
	"LastHoldReasonSubCode",
	"LastJobStatus",
	"LocalSysCpu",
	"LocalUserCpu",
	"MachineAttrCpus0",
	"MachineAttrSlotWeight0",
	"MachineCount",
	"MATCH_EXP_JOB_GLIDEIN_Job_Max_Time",
	"MATCH_EXP_JOB_GLIDEIN_Max_Walltime",
	"MATCH_EXP_JOB_GLIDEIN_MaxMemMBs",
	"MATCH_EXP_JOB_GLIDEIN_Memory",
	"MATCH_EXP_JOB_GLIDEIN_ProcId",
	"MATCH_EXP_JOB_GLIDEIN_ToDie",
	"MATCH_EXP_JOB_GLIDEIN_ToRetire",
	"MaxHosts",
	"MaxJobRetirementTime",
	"MaxTransferInputMB",
	"MaxTransferOutputMB",
	"MaxWallTimeMins_RAW",
	"MaxWallTimeMins",
	"MemoryProvisioned",
	"MemoryUsage",
	"MinHosts",
	"NextJobStartDelay",
	"NoopJobExitCode",
	"NoopJobExitSignal",
	"NumCkpts_RAW",
	"NumCkpts",
	"NumJobCompletions",
	"NumJobMatches",
	"NumJobReconnects",
	"NumJobStarts",
	"NumPids",
	"NumRestarts",
	"NumShadowExceptions",
	"NumShadowStarts",
	"NumSystemHolds",
	"OnExitHoldSubCode",
	"OrigMaxHosts",
	"OutSize",
	"PeriodicHoldSubCode",
	"PilotRestLifeTimeMins",
	"PostCmdExitCode",
	"PostCmdExitSignal",
	"PostJobPrio1",
	"PostJobPrio2",
	"PreCmdExitCode",
	"PreCmdExitSignal",
	"PreJobPrio1",
	"PreJobPrio2",
	"ProcId",
	"ProportionalSetSizeKb",
	"RecentBlockReadKbytes",
	"RecentBlockReads",
	"RecentBlockWriteKbytes",
	"RecentBlockWrites",
	"RecentStatsLifetimeStarter",
	"RemoteSlotID",
	"RemoteSysCpu",
	"RemoteUserCpu",
	"RemoteWallClockTime",
	"RequestCpus",
	"RequestDisk",
	"RequestGpus",
	"RequestMemory",
	"RequestVirtualMemory",
	"ResidentSetSize_RAW",
	"ResidentSetSize",
	"ScratchDirFileCount",
	"StackSize",
	"StatsLifetimeStarter",
	"SuccessCheckpointExitCode",
	"SuccessCheckpointExitSignal",
	"SuccessPostExitCode",
	"SuccessPostExitSignal",
	"SuccessPreExitCode",
	"SuccessPreExitSignal",
	"TotalSubmitProcs",
	"TotalSuspensions",
	"TransferInputSizeMB",
	"WallClockCheckpoint",
	"WindowsBuildNumber",
	"WindowsMajorVersion",
	"WindowsMinorVersion",
}

// date_attrs (38 attrs)
var dateAttrs = []string{
	"CompletionDate",
	"EnteredCurrentStatus",
	"GLIDEIN_ToDie",
	"GLIDEIN_ToRetire",
	"JobCurrentFinishTransferInputDate",
	"JobCurrentFinishTransferOutputDate",
	"JobCurrentStartDate",
	"JobCurrentStartExecutingDate",
	"JobCurrentStartTransferInputDate",
	"JobCurrentStartTransferOutputDate",
	"JobDisconnectedDate",
	"JobFinishedHookDone",
	"JobLastStartDate",
	"JobLeaseExpiration",
	"JobQueueBirthdate",
	"JobStartDate",
	"LastJobLeaseRenewal",
	"LastMatchTime",
	"LastRejMatchTime",
	"LastRemoteStatusUpdate",
	"LastSuspensionTime",
	"LastVacateTime_RAW",
	"LastVacateTime",
	"MATCH_GLIDEIN_ToDie",
	"MATCH_GLIDEIN_ToRetire",
	"QDate",
	"RecordTime",
	"ShadowBday",
	"StageInFinish",
	"StageInStart",
	"StageOutFinish",
	"StageOutStart",
	"TransferInFinished",
	"TransferInQueued",
	"TransferInStarted",
	"TransferOutFinished",
	"TransferOutQueued",
	"TransferOutStarted",
}

// bool_attrs (63 attrs)
var boolAttrs = []string{
	"BufferFiles",
	"CurrentStatusUnknown",
	"DataflowJobSkipped",
	"DockerOverrideEntrypoint",
	"EncryptExecuteDirectory",
	"EraseOutputAndErrorOnRestart",
	"ExitBySignal",
	"GlobusResubmit",
	"IsNoopJob",
	"JobCoreDumped",
	"LeaveJobInQueue",
	"LoadProfile",
	"ManifestDesired",
	"NiceUser",
	"Nonessential",
	"OnExitHold",
	"OnExitRemove",
	"PeriodicHold",
	"PeriodicRelease",
	"PeriodicRemove",
	"PostCmdExitBySignal",
	"PreCmdExitBySignal",
	"PreserveRelativeExecutable",
	"PreserveRelativePaths",
	"RunAsOwner",
	"SendCredential",
	"SkipIfDataflow",
	"SpoolOnEvict",
	"StreamErr",
	"StreamIn",
	"StreamOut",
	"SuccessCheckpointExitBySignal",
	"SuccessPostExitBySignal",
	"SuccessPreExitBySignal",
	"TerminationPending",
	"TransferErr",
	"TransferExecutable",
	"TransferIn",
	"TransferOut",
	"TransferQueued",
	"TransferringInput",
	"TransferringOutput",
	"Use_x509UserProxy",
	"UserLogUseXML",
	"WantAdRevaluate",
	"WantCheckpoint",
	"WantCheckpointSignal",
	"WantClaiming",
	"WantCompletionVisaFromSchedD",
	"WantDelayedUpdates",
	"WantExecutionVisaFromStarter",
	"WantFTOnCheckpoint",
	"WantGracefulRemoval",
	"WantIOProxy",
	"WantMatchDiagnostics",
	"WantMatching",
	"WantParallelScheduling",
	"WantParallelSchedulingGroups",
	"WantPslotPreemption",
	"WantRemoteIO",
	"WantRemoteSyscalls",
	"WantRemoteUpdates",
	"WantResAd",
}

// nested_attrs (5 attrs)
var nestedAttrs = []string{
	"DAG_Stats",
	"NumHoldsByReason",
	"ToE",
	"TransferInputStats",
	"TransferOutputStats",
}

// ignore_attrs (42 attrs)
var ignoreAttrs = []string{
	"AzureAdminKey",
	"AzureAdminUsername",
	"AzureAuthFile",
	"ClaimId",
	"CmdHash",
	"EC2AccessKeyId",
	"EC2KeyPair",
	"EC2KeyPairFile",
	"EC2SecretAccessKey",
	"EC2SecurityGroups",
	"EC2SecurityIDs",
	"EC2UserData",
	"EC2UserDataFile",
	"Env",
	"EnvDelim",
	"Environment",
	"ExecutableSize",
	"GceAccount",
	"GceAuthFile",
	"GceJsonFile",
	"GceMetadataFile",
	"GlideinCredentialIdentifier",
	"GlideinSecurityClass",
	"JobCoreFileName",
	"JobNotification",
	"KeystoreAlias",
	"KeystoreFile",
	"KeystorePassphraseFile",
	"LastPublicClaimId",
	"PostArgs",
	"PostArguments",
	"PostEnv",
	"PostEnvironment",
	"PreArgs",
	"PreArguments",
	"PreEnv",
	"PreEnvironment",
	"PublicClaimId",
	"ScitokensFile",
	"SpooledOutputFiles",
	"orig_environment",
	"osg_environment",
}

var statusNames = map[int64]string{
	0: "Unexpanded",
	1: "Idle",
	2: "Running",
	3: "Removed",
	4: "Completed",
	5: "Held",
	6: "Error",
}

var universeNames = map[int64]string{
	1:  "Standard",
	2:  "Pipe",
	3:  "Linda",
	4:  "PVM",
	5:  "Vanilla",
	6:  "PVMD",
	7:  "Scheduler",
	8:  "MPI",
	9:  "Grid",
	10: "Java",
	11: "Parallel",
	12: "Local",
}
